version: '3.7'

services:
  nutstash:
    image: nutstash
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - 'linux/amd64'
        - 'linux/arm64'
    user: '1000:1000'
    restart: on-failure
    ports:
      - '3000:3000'
    volumes:
      - /tmp/nutstash/nutstash-data:/app/data

volumes:
  nutstash-data: 
